# Generated by Django 2.2.5 on 2019-09-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='img_path',
            field=models.FilePathField(default=''),
        ),
        migrations.AddField(
            model_name='sample',
            name='label',
            field=models.IntegerField(default=10),
        ),
    ]
