# Generated by Django 2.2.5 on 2019-09-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20190914_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='sample',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='sample',
            name='label',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sample',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
